config/routes.rb
Rails.application.routes.draw do
  root to: 'images#index'
  get 'sessions/login', to: 'sessions#login'
  post 'sessions/login', to: 'sessions#authenticate'
  get 'sessions/logout', to: 'sessions#logout'
  post 'favorites', to: 'favorites#favorite'
  delete 'favorites', to: 'favorites#unfavorite'
  resources :users
  resources :images

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :image
  validates_presence_of :user_id
  validates_presence_of :image_id
end

app/models/image.rb
class Image < ActiveRecord::Base
  if Rails.env == "production"
    has_attached_file :data,
                      :styles => {
                          :thumb  => "100x100",
                          :medium => "200x200",
                          :large => "600x400"
                      },
                      :storage => :s3,
                      :s3_permissions => :private,
                      :s3_credentials => "#{Rails.root}/config/s3.yml",
                      :path => ":attachment/:id/:style.:extension"
  else
    has_attached_file :data,
                      :styles => {
                          :thumb  => "100x100",
                          :medium => "200x200",
                          :large => "600x400"
                      },
                      :storage => :filesystem,
                      :path => ":rails_root/public/:attachment/:updated_at/:id/:style.:extension",
                      :url  => "#{ActionController::Base.relative_url_root}/:attachment/:updated_at/:id/:style.:extension"
  end
  validates_presence_of :data
  validates_attachment_content_type :data, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_presence_of :title
  has_many :favorites
  belongs_to :user

  def authenticated_image_url(style)
    if Rails.env == "production"
      data.s3_object(style).url_for(:read, :secure => true)
    else
      data.url(style)
    end
  end
end

app/models/user.rb
# coding: utf-8
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :name, message: 'その名前は既に利用されています'
  validates_presence_of :name
  validates_presence_of :password_digest
  has_many :images
  has_many :favorites
end

app/controllers/favorites_controller.rb
# coding: utf-8
class FavoritesController < ApplicationController
  before_action :login?, only: [:favorite, :unfavorite]
  before_action :set_image, only: [:favorite, :unfavorite]
  def favorite
    user_fav = @current_user.favorites.where(favorite_params)
    if !user_fav.empty?
      return redirect_to image_path(id: @image), notice: '既にお気に入りになっています'
    end
    fav = @current_user.favorites.build(favorite_params)
    if fav.save
      return redirect_to image_path(id: @image), notice: 'お気に入りに登録しました'
    else
    end
  end
  def unfavorite
    user_fav = @current_user.favorites.where(favorite_params)
    if user_fav.empty?
      return redirect_to image_path(id: @image), alert: 'お気に入りに登録されていません'
    end
    user_fav[0].destroy
    return redirect_to image_path(id: @image), notice: 'お気に入りから解除しました'
  end
  private
  def favorite_params
    params.require(:favorite).permit(:image_id)
  end
  def set_image
    @image = Image.find(favorite_params[:image_id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :login?, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
    respond_to do |format|
      if @current_user.id != @image.user.id
        format.html{redirect_to '/', notice: 'Can not edit.'}
      else
        format.html{render :edit }
      end
    end
  end

  # POST /images
  # POST /images.json
  def create
    @image = @current_user.images.build(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    if @current_user.id == @image.user.id
     @image.destroy
     respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
    else
      respond_to do |format|
        format.html {redirect_to '/', notice: 'Don\'t have authority to delete image'}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :data)
    end
end

app/controllers/sessions_controller.rb
# coding: utf-8
class SessionsController < ApplicationController
  before_action :login?, only: [:logout]
  def login
  end

  def authenticate
    user = User.find_by(name: user_params[:name])
    if user && user.authenticate(user_params[:password])
      session[:user_id] = user.id
      redirect_to images_path, notice: 'ログインしました'
    else
      redirect_to sessions_login_path, alert: 'ログインに失敗しました'
    end
  end

  def logout
    @current_user = nil
    reset_session
    redirect_to images_path, notice: 'ログアウトしました'
  end
  private
  def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login?, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.order("created_at desc")
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    respond_to do |format| #add
      if @current_user.id != @user.id
        format.html{redirect_to @user, notice: 'Can not edit.'}
      else
        format.html{render :edit }
      end
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }

      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @current_user.id == @user.id
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/_form.html.erb
<%= form_for(@image, class: "form") do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation row">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field form-group">
      <%= f.label :data %><br>
      <%= f.file_field :data%>
  </div>
  <div class="actions">
    <%= f.submit "登録", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/images/_image.html.erb
<%= image_tag(image.authenticated_image_url(:thumb)) if image.data.present? %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>
<% if @current_user.id == @image.user.id %>
  <%= render 'form' %>
<% end %>

app/views/images/index.html.erb
<div class="row">
<p id="notice"><%= notice %></p>
</div>
<div class="row">
    <h1>Listing Images</h1>
    <%= link_to 'New Image', new_image_path, class: "btn btn-success pull-right" %>
</div>
<table class="table">
  <thead>
    <tr>
        <th>Title</th>
        <th>Image</th>
        <th>Fav?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.title %></td>
        <td><%= image_tag(image.authenticated_image_url(:thumb)) if image.data.present? %></td>
        <td>
            <% if @current_user && !@current_user.favorites.select{|img| img.id == image.id}.empty? %>
                favorite
            <%else%>
            <%end%>
        </td>
        <td><%= link_to 'Show', image, class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<div class="row">
<p id="notice"><%= notice %></p>
</div>
<% if @current_user %>
<div class="row">
  <% if @current_user.id == @image.user.id %>
    <%= link_to 'Destroy', @image, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right" %>
    <%= link_to 'Edit', edit_image_path(@image), class: "btn btn-warning pull-right" %>
  <% end %>
</div>
<% end %>
<div class="row">
    <h3>Title: <%= @image.title %></h3>
    <%= image_tag(@image.authenticated_image_url(:large)) if @image.data.present? %>
</div>
<% if @current_user %>
    <%= link_to 'Favorite', {controller: 'favorites', action: 'favorite', favorite:{image_id: @image} }, :method => :post, class:"btn btn-primary" %>
    <%= link_to 'UnFavorite', {controller: 'favorites', action: 'unfavorite', favorite:{image_id: @image} }, :method => :delete, class: "btn btn-danger"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImgFav</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
          <a href="/" class="navbar-brand">ImgFav</a>
          <ul class="nav navbar-nav navbar-right">
          <% if !@current_user %>
              <li><%= link_to "新規登録", new_user_path %></li>
              <li><%= link_to "ログイン", sessions_login_path  %></li>
          <% else %>
              <li><%= link_to "マイページ", user_path(@current_user) %></li>
              <li><%= link_to "ログアウト", sessions_logout_path%></li>
          <% end%>
          </ul>
        </div>
    </nav>
    <div class="container">
        <%= yield %>
    </div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user, class: "form") do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password, class:"form-control" %>
  </div>
  <div class="field form-group">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, class:"form-control" %>
  </div>
  <div class="actions">
      <%= f.submit "登録", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %>

app/views/users/index.html.erb
<div class="row">
<p id="notice"><%= notice %></p>
</div>
<div class="row">
<h1>Listing Users</h1>
</div>
<table class="table">
  <thead>
    <tr>
        <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
<p id="notice"><%= notice %></p>
</div>
<% if @current_user %>
<div class="row">
  <% if @current_user.id == @user.id %>
    <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger col-md-1 pull-right" %>
    <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-warning col-md-1 pull-right" %>
  <% end %>
</div>
<% end %>
<div class="row">
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
</div>